package View;


import Controller.StatsController;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;


public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    public MainFrame() {
        initComponents();
        //Text field for static infos are set and radiobutton are configured
        numusertf.setText(statC.getTots(3));
        numeventstf.setText(statC.getTots(1));
        ticketsoldtf.setText(statC.getTots(2));
        radiobuttIncassi.setActionCommand("Incassi");
        radiobuttBigliettiVenduti.setActionCommand("BigliettiVenduti");
        
    }
    StatsController statC = new StatsController();
    
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titlab = new javax.swing.JLabel();
        tsbd = new javax.swing.JLabel();
        tsbdpiebutt = new javax.swing.JButton();
        tsbdbarbutt = new javax.swing.JButton();
        tsbdlinebutt = new javax.swing.JButton();
        tsbcat = new javax.swing.JLabel();
        tsbcatbar = new javax.swing.JButton();
        tsbcatpie = new javax.swing.JButton();
        ebdlab = new javax.swing.JLabel();
        ebdbutt = new javax.swing.JButton();
        ebdbar = new javax.swing.JButton();
        ebdline = new javax.swing.JButton();
        ebclab = new javax.swing.JLabel();
        ebcpie = new javax.swing.JButton();
        ebcbar = new javax.swing.JButton();
        numuser = new javax.swing.JLabel();
        numusertf = new javax.swing.JTextField();
        numevents = new javax.swing.JLabel();
        numeventstf = new javax.swing.JTextField();
        ticketsoldlab = new javax.swing.JLabel();
        ticketsoldtf = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        rapidlab = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        customresearchlab = new javax.swing.JLabel();
        datainizio = new com.toedter.calendar.JDateChooser();
        datafine = new com.toedter.calendar.JDateChooser();
        comboboxcategoria = new javax.swing.JComboBox<>();
        radiobuttIncassi = new javax.swing.JRadioButton();
        radiobuttBigliettiVenduti = new javax.swing.JRadioButton();
        customrespie = new javax.swing.JButton();
        customresbar = new javax.swing.JButton();
        customresline = new javax.swing.JButton();
        intervallolab = new javax.swing.JLabel();
        categlab = new javax.swing.JLabel();
        filterlab = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlab.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        titlab.setText("STATISTICHE");

        tsbd.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        tsbd.setText("Biglietti venduti per data");

        tsbdpiebutt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rsz_piechic.png"))); // NOI18N
        tsbdpiebutt.setText("Torta");
        tsbdpiebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsbdpiebuttActionPerformed(evt);
            }
        });

        tsbdbarbutt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/barchart.png"))); // NOI18N
        tsbdbarbutt.setText("Barre");
        tsbdbarbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsbdbarbuttActionPerformed(evt);
            }
        });

        tsbdlinebutt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/linechart.png"))); // NOI18N
        tsbdlinebutt.setText("Lineare");
        tsbdlinebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsbdlinebuttActionPerformed(evt);
            }
        });

        tsbcat.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        tsbcat.setText("Biglietti venduti per categoria");

        tsbcatbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/barchart.png"))); // NOI18N
        tsbcatbar.setText("Barre");
        tsbcatbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsbcatbarActionPerformed(evt);
            }
        });

        tsbcatpie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rsz_piechic.png"))); // NOI18N
        tsbcatpie.setText("Torta");
        tsbcatpie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsbcatpieActionPerformed(evt);
            }
        });

        ebdlab.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        ebdlab.setText("Incassi biglietti per data");

        ebdbutt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rsz_piechic.png"))); // NOI18N
        ebdbutt.setText("Torta");
        ebdbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebdbuttActionPerformed(evt);
            }
        });

        ebdbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/barchart.png"))); // NOI18N
        ebdbar.setText("Barre");
        ebdbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebdbarActionPerformed(evt);
            }
        });

        ebdline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/linechart.png"))); // NOI18N
        ebdline.setText("Lineare");
        ebdline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebdlineActionPerformed(evt);
            }
        });

        ebclab.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        ebclab.setText("Incassi biglietti per categoria");

        ebcpie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rsz_piechic.png"))); // NOI18N
        ebcpie.setText("Torta");
        ebcpie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebcpieActionPerformed(evt);
            }
        });

        ebcbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/barchart.png"))); // NOI18N
        ebcbar.setText("Barre");
        ebcbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebcbarActionPerformed(evt);
            }
        });

        numuser.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        numuser.setText("Utenti registrati:");

        numusertf.setEditable(false);
        numusertf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numusertfActionPerformed(evt);
            }
        });

        numevents.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        numevents.setText("Eventi disponibili:");

        numeventstf.setEditable(false);

        ticketsoldlab.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        ticketsoldlab.setText("Biglietti venduti:");

        ticketsoldtf.setEditable(false);
        ticketsoldtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketsoldtfActionPerformed(evt);
            }
        });

        rapidlab.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        rapidlab.setText("GRAFICI RAPIDI");

        customresearchlab.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        customresearchlab.setText("RICERCA PERSONALIZZATA");

        comboboxcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TUTTE", "CONCERTO", "SPORT", "MANIFESTAZIONE" }));

        buttonGroup1.add(radiobuttIncassi);
        radiobuttIncassi.setSelected(true);
        radiobuttIncassi.setText("Incassi");
        radiobuttIncassi.setToolTipText("");
        radiobuttIncassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobuttIncassiActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobuttBigliettiVenduti);
        radiobuttBigliettiVenduti.setText("Biglietti venduti");

        customrespie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rsz_piechic.png"))); // NOI18N
        customrespie.setText("Torta");
        customrespie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customrespieActionPerformed(evt);
            }
        });

        customresbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/barchart.png"))); // NOI18N
        customresbar.setText("Barre");
        customresbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customresbarActionPerformed(evt);
            }
        });

        customresline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/linechart.png"))); // NOI18N
        customresline.setText("Lineare");
        customresline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customreslineActionPerformed(evt);
            }
        });

        intervallolab.setText("Intervallo Temporale");

        categlab.setText("Categoria");

        filterlab.setText("Filtro");

        jButton11.setText("CHIUDI");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(numuser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numusertf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(numevents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeventstf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(ticketsoldlab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ticketsoldtf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(rapidlab))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(tsbd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(tsbdpiebutt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tsbdbarbutt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tsbdlinebutt))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(ebdlab))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ebcpie)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ebcbar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tsbcatpie)
                                        .addGap(31, 31, 31)
                                        .addComponent(tsbcatbar))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(tsbcat)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(ebclab)
                                        .addGap(93, 93, 93))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ebdbutt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ebdbar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ebdline)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiobuttIncassi)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(datainizio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(datafine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(radiobuttBigliettiVenduti)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(categlab)
                                .addGap(177, 177, 177))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(intervallolab)
                                .addGap(149, 149, 149))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(customrespie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(customresbar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(customresline)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(customresearchlab)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(comboboxcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(filterlab)
                                .addGap(189, 189, 189))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(titlab)
                        .addGap(337, 337, 337))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(348, 348, 348))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(titlab)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numuser)
                    .addComponent(numusertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numevents)
                    .addComponent(numeventstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketsoldlab)
                    .addComponent(ticketsoldtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rapidlab)
                    .addComponent(customresearchlab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tsbd)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tsbdpiebutt)
                            .addComponent(tsbdbarbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tsbdlinebutt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ebdlab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ebdbutt)
                            .addComponent(ebdbar)
                            .addComponent(ebdline))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tsbcat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tsbcatpie)
                            .addComponent(tsbcatbar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ebclab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ebcpie)
                            .addComponent(ebcbar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datainizio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(intervallolab)
                                .addGap(19, 19, 19)
                                .addComponent(datafine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(categlab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboboxcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(filterlab)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(customrespie)
                                    .addComponent(customresbar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customresline)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radiobuttIncassi)
                                    .addComponent(radiobuttBigliettiVenduti))))))
                .addGap(61, 61, 61)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Fast Chart buttons, right method is called
    private void tsbdpiebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsbdpiebuttActionPerformed
        statC.fastCharts(4);
        
    }//GEN-LAST:event_tsbdpiebuttActionPerformed

    private void tsbdbarbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsbdbarbuttActionPerformed
        statC.fastCharts(5);
        
    }//GEN-LAST:event_tsbdbarbuttActionPerformed

    private void tsbdlinebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsbdlinebuttActionPerformed
        statC.fastCharts(6);
        
    }//GEN-LAST:event_tsbdlinebuttActionPerformed

    private void tsbcatbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsbcatbarActionPerformed
        statC.fastCharts(8);
        
    }//GEN-LAST:event_tsbcatbarActionPerformed

    private void tsbcatpieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsbcatpieActionPerformed
        statC.fastCharts(7);
        
    }//GEN-LAST:event_tsbcatpieActionPerformed

    private void ebdbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebdbuttActionPerformed
        statC.fastCharts(1);
        
    }//GEN-LAST:event_ebdbuttActionPerformed

    private void ebdbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebdbarActionPerformed
        statC.fastCharts(2);
        
    }//GEN-LAST:event_ebdbarActionPerformed

    private void ebdlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebdlineActionPerformed
        statC.fastCharts(3);
        
    }//GEN-LAST:event_ebdlineActionPerformed

    private void ebcpieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebcpieActionPerformed
        statC.fastCharts(9);
        
    }//GEN-LAST:event_ebcpieActionPerformed

    private void ebcbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebcbarActionPerformed
        statC.fastCharts(10);
        
    }//GEN-LAST:event_ebcbarActionPerformed

    private void numusertfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numusertfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numusertfActionPerformed

    private void ticketsoldtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketsoldtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketsoldtfActionPerformed

    private void radiobuttIncassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobuttIncassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobuttIncassiActionPerformed

    private void customrespieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customrespieActionPerformed
        java.util.Date utilStartDate = datainizio.getDate();
        java.util.Date utilEndtDate = datafine.getDate();
        //If one of the dates is null an error is shown and user must fill the info
        if(utilStartDate == null || utilEndtDate == null){
            JOptionPane.showMessageDialog(null, "Uno dei campi data è vuoto!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //Else charts are displayed
        else{
            java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
            java.sql.Date sqlEndDate = new java.sql.Date(utilEndtDate.getTime());
            statC.resChart(sqlStartDate, sqlEndDate, comboboxcategoria.getItemAt(comboboxcategoria.getSelectedIndex()), buttonGroup1.getSelection().getActionCommand(), "pie");
        }
    }//GEN-LAST:event_customrespieActionPerformed

    private void customresbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customresbarActionPerformed
        java.util.Date utilStartDate = datainizio.getDate();
        java.util.Date utilEndtDate = datafine.getDate();
        if(utilStartDate == null || utilEndtDate == null){
            JOptionPane.showMessageDialog(null, "Uno dei campi data è vuoto!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
            java.sql.Date sqlEndDate = new java.sql.Date(utilEndtDate.getTime());
            statC.resChart(sqlStartDate, sqlEndDate, comboboxcategoria.getItemAt(comboboxcategoria.getSelectedIndex()), buttonGroup1.getSelection().getActionCommand(), "bar");
        }
    }//GEN-LAST:event_customresbarActionPerformed

    private void customreslineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customreslineActionPerformed
        java.util.Date utilStartDate = datainizio.getDate();
        java.util.Date utilEndtDate = datafine.getDate();
        if(utilStartDate == null || utilEndtDate == null){
            JOptionPane.showMessageDialog(null, "Uno dei campi data è vuoto!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
            java.sql.Date sqlEndDate = new java.sql.Date(utilEndtDate.getTime());
            statC.resChart(sqlStartDate, sqlEndDate, comboboxcategoria.getItemAt(comboboxcategoria.getSelectedIndex()), buttonGroup1.getSelection().getActionCommand(), "line");
        }
    }//GEN-LAST:event_customreslineActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel categlab;
    private javax.swing.JComboBox<String> comboboxcategoria;
    private javax.swing.JButton customresbar;
    private javax.swing.JLabel customresearchlab;
    private javax.swing.JButton customresline;
    private javax.swing.JButton customrespie;
    private com.toedter.calendar.JDateChooser datafine;
    private com.toedter.calendar.JDateChooser datainizio;
    private javax.swing.JButton ebcbar;
    private javax.swing.JLabel ebclab;
    private javax.swing.JButton ebcpie;
    private javax.swing.JButton ebdbar;
    private javax.swing.JButton ebdbutt;
    private javax.swing.JLabel ebdlab;
    private javax.swing.JButton ebdline;
    private javax.swing.JLabel filterlab;
    private javax.swing.JLabel intervallolab;
    private javax.swing.JButton jButton11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel numevents;
    private javax.swing.JTextField numeventstf;
    private javax.swing.JLabel numuser;
    private javax.swing.JTextField numusertf;
    private javax.swing.JRadioButton radiobuttBigliettiVenduti;
    private javax.swing.JRadioButton radiobuttIncassi;
    private javax.swing.JLabel rapidlab;
    private javax.swing.JLabel ticketsoldlab;
    private javax.swing.JTextField ticketsoldtf;
    private javax.swing.JLabel titlab;
    private javax.swing.JLabel tsbcat;
    private javax.swing.JButton tsbcatbar;
    private javax.swing.JButton tsbcatpie;
    private javax.swing.JLabel tsbd;
    private javax.swing.JButton tsbdbarbutt;
    private javax.swing.JButton tsbdlinebutt;
    private javax.swing.JButton tsbdpiebutt;
    // End of variables declaration//GEN-END:variables
}
